# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oz2cdqwRIoHySecTkgNsARi9gD2yN2gu
"""

import requests
from bs4 import BeautifulSoup
from fpdf import FPDF

url = "https://greenifyai.com/ai/glossary_one_big_text.php"
response = requests.get(url)

def save_text_as_pdf(text_content, output_file):
    
    pdf = FPDF()

    pdf.add_page()

    pdf.set_font("Arial", size = 12)

    pdf.multi_cell(0, 10, text_content.encode("utf-8").decode("latin-1"))
    

    pdf.output(output_file+".pdf")

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'html.parser')

    # Target the specific container div
    data_container = soup.find('div', class_='container alf')

    if data_container:
        # Extract text within the container
        scraped_text = data_container.get_text(separator='\n').strip()
        #print(scraped_text)
        output_file = "One_Big_Text"

# Save text content as PDF
        save_text_as_pdf(scraped_text, output_file)


    else:
        print("Container div with class 'container alf' not found on the page.")

else:
    print(f"Error: Failed to retrieve data from {url} (status code: {response.status_code})")